#!/bin/bash

declare -A stn_name=(["hb"]="Hobart 12" ["ke"]="Katherine 12" ["yg"]="Yarragadee 12" ["ho"]="Hobart 26")

# using -t stops ssh doign line buffering 
ssh pcfs$1 ./delaymon  |
unbuffer -p feedgnuplot --stream  \
            --domain  \
            --timefmt '%Y.%j.%H:%M:%S' \
            --title "Delay difference at ${stn_name[$1]}" \
            --set 'format x "%H:%M"'  \
            --set 'mouse mouseformat 3'  >/dev/null 

