#!/bin/sh
#Print the Field System log to stdout 

LOG=$(lognm)

set +b

tail -n 0 -f /usr2/log/$LOG.log 2>/dev/null &
PID=$!

while true; do
    NEW=$(lognm)
    if [ "$NEW" != "$LOG" ]; then
        kill $PID
        # Only print the whole file if it's new. This avoids, e.g., printing the whole stations log when switching to it.
        if [ $(date -r /usr2/log/${NEW}.log +%s) -lt $(date +%s --date="5 min ago") ]; then
            tail -n+1 -f /usr2/log/${NEW}.log 2>/dev/null &
        else
            tail -n 0 -f /usr2/log/${NEW}.log 2>/dev/null &
        fi
        PID=$!
        LOG=$NEW
    fi
    sleep 1
done
