#!/bin/bash

#Keep persistent connection
SSH='ssh -q -o ControlMaster=auto -o ControlPath=~/.ssh/tail-%r@%h:%p -o ControlPersist=10m '
PCFS=pcfske

LOG=$($SSH $PCFS lognm)

$SSH $PCFS tail -n 0 -f /usr2/log/$LOG.log &
PID=$!

#Kill ssh tail on exit 
#trap 'kill $(jobs -p)' EXIT

while true; do
    NEW=$($SSH $PCFS lognm)
    if [ "$NEW" != "$LOG" ]; then
        kill $PID
        # Only print the whole file if its new. This avoids eg printing the whole stations file when switching to it.
        if [ $(ssh date -r /usr2/log/${NEW}.log +%s) -lt $(ssh date +%s --date="5 min ago") ]; then
            $SSH $PCFS tail -n+1 -f /usr2/log/${NEW}.log &
        else
            $SSH $PCFS tail -n 0 -f /usr2/log/${NEW}.log &
        fi
        PID=$!
        LOG=$NEW
    fi
    sleep 1
done
