#!/usr/bin/env python2
from __future__ import print_function
#import time
from datetime import datetime, timedelta
import sys
import os
import os.path
from urllib import urlretrieve

import argparse
parser = argparse.ArgumentParser(description='Find the next experiment containing at least one of the given stations.')
parser.add_argument('stns', nargs='*', default=['hb', 'ke', 'yg', 'ho'], help='stations to consider (default "hb ke yg ho")')
parser.add_argument('-p', '--print-stations', action='store_true', help='print which of stns are invloved in found experiment.')
parser.add_argument('-a', '--all', action='store_true', help='find next the experiment with all "stns" in it ')

args = parser.parse_args()

stns = set(args.stns)

now = datetime.utcnow()
year = now.year - 2000

mstr = '/vlbobs/ivs/master%d.txt'%year
#Check for new master file if we haven't done so in a day
if not os.path.isfile(mstr) or now > datetime.utcfromtimestamp(os.path.getmtime(mstr)) + timedelta(1):
    os.chdir('/vlbobs/ivs/')
    os.system('wget -q -N ftp://cddis.gsfc.nasa.gov/pub/vlbi/ivscontrol/master%d.txt'%year)
    os.utime(mstr,None)
    
f = open(mstr,'r')

def parse_station(s):
    s = s.split(' ')[0]
    stns = set()
    for i in range(len(s)/2):
        stns.add(s[2*i:2*i+2].lower())
    return stns

for l in f.readlines():
    if l.startswith('|'):
        ses = l.strip(' |\n').split('|')
        ses_time = datetime.strptime("%d %s %s"%(now.year, ses[2], ses[4]), "%Y %b%d %H:%M")
        
        if ses_time >= now:
            ses_stns  = parse_station(ses[6])
            our_stns_in_exp = stns.intersection(ses_stns)
            if (not args.all and our_stns_in_exp != set()) or (args.all and our_stns_in_exp == stns):
                ses_code = ses[1].strip().lower()
                break

if args.print_stations:
    print(ses_code, " ".join(sorted(list(our_stns_in_exp))))
else:
    print(ses_code)

